platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'RokuRemoteApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])


  target 'RokuRemoteAppTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end

target 'RokuRemoteApp-tvOS' do
  # Pods for RokuRemoteApp-tvOS

  target 'RokuRemoteApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
